// Workaround needed for nexus publishing bug
// version and group must be specified in the root project
// https://github.com/gradle-nexus/publish-plugin/issues/310
version = projectVersion
group = 'io.github.matrei'
subprojects {
    if (name == 'grails-csrf') {
        apply plugin: 'org.apache.grails.gradle.grails-publish'
    }
}
