[versions]
assetpipeline-grails = '4.5.2'
grails = '6.2.2'
grails-geb = '4.1.1'
grails-gsp = '6.2.1'
grails-testing-support = '3.2.2'
groovy = '3.0.25'
java-baseline = '11'
servlet-api = '4.0.1'
micronaut = '3.10.4'
slf4j = '1.7.36'
spock = '2.3-groovy-3.0'
spring = '5.3.39'
springboot = '2.7.18'

[libraries]
assetpipeline-grails = { module = 'com.bertramlabs.plugins:asset-pipeline-grails', version.ref='assetpipeline-grails' }
grails-core = { module = 'org.grails:grails-core', version.ref = 'grails' }
grails-geb = { module = 'org.grails.plugins:geb', version.ref = 'grails-geb' }
grails-gsp = { module = 'org.grails.plugins:gsp', version.ref = 'grails-gsp' }
grails-i18n = { module = 'org.grails:grails-plugin-i18n', version.ref = 'grails' }
grails-interceptor = { module = 'org.grails:grails-plugin-interceptors', version.ref = 'grails' }
grails-testingsupport-web = { module = 'org.grails:grails-web-testing-support', version.ref = 'grails-testing-support' }
grails-urlmappings = { module = 'org.grails:grails-plugin-url-mappings', version.ref = 'grails' }
groovy-core = { module = 'org.codehaus.groovy:groovy', version.ref = 'groovy' }
micronaut-inject = { module = 'io.micronaut:micronaut-inject', version.ref = 'micronaut' }
micronaut-inject-groovy = { module = 'io.micronaut:micronaut-inject-groovy', version.ref = 'micronaut' }
servlet-api = { module = 'javax.servlet:javax.servlet-api', version.ref = 'servlet-api' }
slf4j-nop = { module = 'org.slf4j:slf4j-nop', version.ref = 'slf4j' }
spock-core = { module = 'org.spockframework:spock-core', version.ref = 'spock' }
spring-context = { module = 'org.springframework:spring-context', version.ref = 'spring' }
spring-web = { module = 'org.springframework:spring-web', version.ref = 'spring' }
springboot-starter = { module = 'org.springframework.boot:spring-boot-starter', version.ref = 'springboot' }
springboot-autoconfigure = { module = 'org.springframework.boot:spring-boot-autoconfigure', version.ref = 'springboot' }
springboot-starter-logging = { module = 'org.springframework.boot:spring-boot-starter-logging', version.ref = 'springboot' }
springboot-starter-tomcat = { module = 'org.springframework.boot:spring-boot-starter-tomcat', version.ref = 'springboot' }