plugins {
    id 'build.config.grails-plugin'
}

ext {
    pomDevelopers = [
        matrei: 'Mattias Reichel',
    ]
}

dependencies {

    compileOnly 'org.apache.grails:grails-core' // Provided
    compileOnly 'org.apache.grails:grails-interceptors' // Provided
    compileOnly 'org.springframework:spring-context' // Provided
    compileOnly 'org.springframework:spring-web' // Provided

    compileOnly 'org.apache.groovy:groovy' // Provided
    compileOnly 'jakarta.servlet:jakarta.servlet-api' // Provided

    testImplementation 'org.apache.grails:grails-testing-support-web'
    testImplementation 'org.spockframework:spock-core'

    testRuntimeOnly 'org.slf4j:slf4j-nop' // Get rid of warning about missing slf4j implementation during test task
}
