plugins {
    id 'build.config.grails-test-app'
    id 'cloud.wondrify.asset-pipeline'
}

dependencies {

    runtimeOnly project(':grails-csrf')

    implementation 'org.apache.grails:grails-dependencies-starter-web'
    implementation 'org.apache.grails:grails-dependencies-assets'

    runtimeOnly 'cloud.wondrify:asset-pipeline-grails'

    testAndDevelopmentOnly 'org.webjars.npm:bootstrap'
    testAndDevelopmentOnly 'org.webjars.npm:bootstrap-icons'
    testAndDevelopmentOnly 'org.webjars.npm:jquery'

    testImplementation project(':grails-csrf'), {
        // impl: CsrfConfig
    }
    testImplementation 'org.apache.grails:grails-testing-support-web'
    testImplementation 'org.spockframework:spock-core'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    integrationTestImplementation testFixtures('org.apache.grails:grails-geb')
}

assets {
    excludes = [
            'webjars/jquery/**',
            'webjars/bootstrap/**',
            'webjars/bootstrap-icons/**'
    ]
    includes = [
            'webjars/jquery/*/dist/jquery.js',
            'webjars/bootstrap/*/dist/js/bootstrap.bundle.js',
            'webjars/bootstrap/*/dist/css/bootstrap.css',
            'webjars/bootstrap-icons/*/font/bootstrap-icons.css',
            'webjars/bootstrap-icons/*/font/fonts/*',
    ]
}
