name: Release Drafter
on:
  issues:
    types: [closed, reopened]
  push:
    branches:
      - main
      - '[1-9]+.[0-9]+.x'
  workflow_dispatch:
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "value=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ steps.extract_branch.outputs.value }}